#!/opt/projects/dev-env/bin/python

from argh import ArghParser
from flask import Flask
from plecnoutils import debugger    
from flask.ext.autoindex import AutoIndex
    
def serve(dir, port=5000, host="localhost", debug=False):
    app = Flask("static_server", static_folder=dir, static_url_path="/")
    AutoIndex(app,  browse_root=dir)
    app.run(host=host, port = port, debug = debug)

    
def main():
    parser = ArghParser()
    parser.add_commands([serve])
    parser.dispatch()
    
if __name__=="__main__":
    main()
